app:
  name: NexusMind
  version: 1.0.0
  assistant: Nexa

system:
  api_port: 9000
  ui_port: 8502

llm:
  temperature: 0.0
  max_tokens: 2048

rag:
  chunk_size: 300
  chunk_overlap: 50
  top_k: 5

  # 🔥 ADD THIS BLOCK
embedding:
  provider: ollama
  model: nomic-embed-text
  dimension: 768

memory:
  max_messages: 50

tools:
  calculator: true
  web_search: true